import { Team, Fixture, MatchEvent, Standing, NewsItem, Episode, AdSlot, MetricSummary } from "./types";

export const WORLD_CUP_TEAMS: Team[] = [
  { id: "usa", name: "United States", badgeUrl: "🇺🇸", group: "A" },
  { id: "mex", name: "Mexico", badgeUrl: "🇲🇽", group: "A" },
  { id: "can", name: "Canada", badgeUrl: "🇨🇦", group: "B" },
  { id: "eng", name: "England", badgeUrl: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "B" },
  { id: "arg", name: "Argentina", badgeUrl: "🇦🇷", group: "C" },
  { id: "bra", name: "Brazil", badgeUrl: "🇧🇷", group: "C" },
  { id: "fra", name: "France", badgeUrl: "🇫🇷", group: "D" },
  { id: "ger", name: "Germany", badgeUrl: "🇩🇪", group: "D" },
  { id: "ita", name: "Italy", badgeUrl: "🇮🇹", group: "E" },
  { id: "spa", name: "Spain", badgeUrl: "🇪🇸", group: "E" },
  { id: "por", name: "Portugal", badgeUrl: "🇵🇹", group: "F" },
  { id: "ned", name: "Netherlands", badgeUrl: "🇳🇱", group: "F" },
  { id: "jpn", name: "Japan", badgeUrl: "🇯🇵", group: "G" },
  { id: "kor", name: "South Korea", badgeUrl: "🇰🇷", group: "G" },
  { id: "aus", name: "Australia", badgeUrl: "🇦🇺", group: "H" },
  { id: "sen", name: " Senegal", badgeUrl: "🇸🇳", group: "H" },
  { id: "mar", name: "Morocco", badgeUrl: "🇲🇦", group: "I" },
  { id: "egy", name: "Egypt", badgeUrl: "🇪🇬", group: "I" },
  { id: "col", name: "Colombia", badgeUrl: "🇨🇴", group: "J" },
  { id: "uru", name: "Uruguay", badgeUrl: "🇺🇾", group: "J" },
  { id: "bel", name: "Belgium", badgeUrl: "🇧🇪", group: "K" },
  { id: "cro", name: "Croatia", badgeUrl: "🇭🇷", group: "K" },
  { id: "sui", name: "Switzerland", badgeUrl: "🇨🇭", group: "L" },
  { id: "cmr", name: "Cameroon", badgeUrl: "🇨🇲", group: "L" },
];

export const INITIAL_FIXTURES: Fixture[] = [
  {
    id: "match-1",
    teamHomeId: "usa",
    teamAwayId: "mex",
    kickoffTime: "2026-06-11T18:00:00Z",
    venue: "Azteca Stadium, Mexico City",
    stage: "Group Stage",
    group: "A",
    status: "live",
    homeScore: 2,
    awayScore: 1,
    minute: 74,
  },
  {
    id: "match-2",
    teamHomeId: "eng",
    teamAwayId: "can",
    kickoffTime: "2026-06-12T20:00:00Z",
    venue: "MetLife Stadium, East Rutherford",
    stage: "Group Stage",
    group: "B",
    status: "live",
    homeScore: 0,
    awayScore: 0,
    minute: 12,
  },
  {
    id: "match-3",
    teamHomeId: "arg",
    teamAwayId: "bra",
    kickoffTime: "2026-06-13T15:00:00Z",
    venue: "SoFi Stadium, Los Angeles",
    stage: "Group Stage",
    group: "C",
    status: "completed",
    homeScore: 3,
    awayScore: 2,
  },
  {
    id: "match-4",
    teamHomeId: "fra",
    teamAwayId: "ger",
    kickoffTime: "2026-06-15T19:00:00Z",
    venue: "Mercedes-Benz Stadium, Atlanta",
    stage: "Group Stage",
    group: "D",
    status: "scheduled",
  },
  {
    id: "match-5",
    teamHomeId: "spa",
    teamAwayId: "ita",
    kickoffTime: "2026-06-16T17:00:00Z",
    venue: "Hard Rock Stadium, Miami",
    stage: "Group Stage",
    group: "E",
    status: "scheduled",
  },
];

export const INITIAL_MATCH_EVENTS: MatchEvent[] = [
  {
    id: "ev-1",
    matchId: "match-1",
    minute: 14,
    type: "goal",
    playerName: "Christian Pulisic",
    teamId: "usa",
  },
  {
    id: "ev-2",
    matchId: "match-1",
    minute: 38,
    type: "card",
    playerName: "Edson Álvarez",
    teamId: "mex",
  },
  {
    id: "ev-3",
    matchId: "match-1",
    minute: 54,
    type: "goal",
    playerName: "Santiago Giménez",
    teamId: "mex",
  },
  {
    id: "ev-4",
    matchId: "match-1",
    minute: 68,
    type: "goal",
    playerName: "Ricardo Pepi",
    teamId: "usa",
  },
];

export const INITIAL_STANDINGS: Standing[] = [
  { groupId: "A", teamId: "usa", played: 1, won: 1, drawn: 0, lost: 0, gd: 1, points: 3 },
  { groupId: "A", teamId: "mex", played: 1, won: 0, drawn: 0, lost: 1, gd: -1, points: 0 },
  { groupId: "B", teamId: "eng", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { groupId: "B", teamId: "can", played: 0, won: 0, drawn: 0, lost: 0, gd: 0, points: 0 },
  { groupId: "C", teamId: "arg", played: 1, won: 1, drawn: 0, lost: 0, gd: 1, points: 3 },
  { groupId: "C", teamId: "bra", played: 1, won: 0, drawn: 0, lost: 1, gd: -1, points: 0 },
];

export const INITIAL_NEWS_ITEMS: NewsItem[] = [
  {
    id: "news-1",
    headline: "Mbappé declared fit for Germany opener in Atlanta",
    body: "The French clinical star completed the full training session in Atlanta and head coach Deschamps confirmed he will lead the Les Bleus attack.",
    source: "Pitchside News Desk",
    verified: true,
    publishedAt: "2026-06-14T10:00:00Z",
    relatedTeamIds: ["fra"],
  },
  {
    id: "news-2",
    headline: "Neymar hints at shock tactical pivot for Group Stage game 2",
    body: "Inside sources suggest Brazil might restructure their front three after the opening defeat to rival Argentina, giving Vinícius Jr more lateral freedom.",
    source: "Generational Football Daily",
    verified: true,
    publishedAt: "2026-06-13T22:30:00Z",
    relatedTeamIds: ["bra"],
  },
  {
    id: "news-3",
    headline: "Argentina team flight delayed due to heavy thunderstorm",
    body: "Messi and teammates was delayed for 4 hours when transitioning to their next training resort, but team officials confirm everyone is well rested.",
    source: "Unverified Tweet Fanatic",
    verified: false,
    publishedAt: "2026-06-14T08:15:00Z",
    relatedTeamIds: ["arg"],
  },
];

export const INITIAL_SPONSORS: AdSlot[] = [
  {
    id: "spon-1",
    type: "banner",
    creativeUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=600",
    clickUrl: "https://soccergear.example.com/discount2026",
    sponsorName: "MaxGear International",
    startDate: "2026-06-10",
    endDate: "2026-07-20",
  },
  {
    id: "spon-2",
    type: "preroll",
    sponsorName: "Puma Kickers",
    clickUrl: "https://puma.example.com",
    startDate: "2026-06-10",
    endDate: "2026-07-20",
  },
];

export const MOCK_METRICS: MetricSummary = {
  dau: 14250,
  concurrent: 1845,
  listeningMins: 34.2,
  completionRate: 74,
  conversions: 4.8,
  impressions: 48900,
  fillRate: 98,
  registeredUsers: 1420,
};

export const INITIAL_EPISODES: Episode[] = [
  {
    id: "1",
    title: "Opening Clash Live from Los Angeles",
    matchName: "USA vs Mexico (Group Stage)",
    language: "English",
    tone: "Dramatic",
    durationSeconds: 120,
    showType: "preview",
    relatedTeamIds: ["usa", "mex"],
    createdAt: "2026-06-11T12:00:00Z",
    tier: "free",
    segments: [
      {
        speaker: "Anchor Mike",
        text: "The stage is finally set! The sun is shining high over Los Angeles, and two eternal neighbors face off. Welcome to MatchDay Radio generically covering the 2026 tournament kickoff!",
        voice: "Zephyr",
        role: "Anchor",
      },
      {
        speaker: "Analyst Sofia",
        text: "Sofia here. Tactically, USA has loaded up the flanks, expecting Pulisic to make diagonal cuts. Mexico's defense must remain compact or get picked apart in the halfspaces.",
        voice: "Kore",
        role: "Analyst",
      },
      {
        speaker: "Reporter Thiago",
        text: "Thiago down by the pitchside turf! I can feel the pure vibrations in this crowd. Over 90,000 passionate fans roaring! This is soccer history in the making!",
        voice: "Puck",
        role: "Reporter",
      },
    ],
  },
  {
    id: "2",
    title: "Live Update: USA Takes the Edge!",
    matchName: "USA vs Mexico (Group Stage)",
    language: "English",
    tone: "Energetic",
    durationSeconds: 60,
    showType: "live-pulse",
    relatedTeamIds: ["usa", "mex"],
    createdAt: "2026-06-11T18:30:00Z",
    tier: "free",
    segments: [
      {
        speaker: "Anchor Mike",
        text: "We interrupt your current feed with a Live Pulse Update! We have a goal in Los Angeles!",
        voice: "Zephyr",
        role: "Anchor",
      },
      {
        speaker: "Reporter Thiago",
        text: "Mike! It is Christian Pulisic with an absolutely stunning half-volley right into the top corner! The USA fans are going into absolute pandemonium here! USA leads one-nil!",
        voice: "Puck",
        role: "Reporter",
      },
    ],
  },
  {
    id: "3",
    title: "Clash of Giants Recap",
    matchName: "Argentina vs Brazil (Group Stage)",
    language: "English",
    tone: "Analytical",
    durationSeconds: 150,
    showType: "recap",
    relatedTeamIds: ["arg", "bra"],
    createdAt: "2026-06-13T17:30:00Z",
    tier: "free",
    segments: [
      {
        speaker: "Anchor Mike",
        text: "What a spectacular match in Los Angeles! Argentina secures a 3-2 victory over Brazil in an intense group battle.",
        voice: "Zephyr",
        role: "Anchor",
      },
      {
        speaker: "Analyst Sofia",
        text: "A high-pressing chess match. Argentina's midfield managed to isolate Vinicius Jr perfectly, while capitalizing or finding gaps to feed crucial breakthroughs.",
        voice: "Kore",
        role: "Analyst",
      },
    ],
  },
  {
    id: "ep-predictions",
    title: "Predictions & Odds: Match Day 5 Forecaster",
    matchName: "France vs Germany (Group Stage)",
    language: "English",
    tone: "Analytical",
    durationSeconds: 140,
    showType: "predictions",
    relatedTeamIds: ["fra", "ger"],
    createdAt: "2026-06-14T20:00:00Z",
    tier: "free",
    segments: [
      {
        speaker: "Anchor Mike",
        text: "Welcome to the forecaster channel. Today we break down odds for the continental derby between France and Germany in Atlanta.",
        voice: "Zephyr",
        role: "Anchor",
      },
      {
        speaker: "Analyst Sofia",
        text: "The bookmakers have France as slight favorites at 2.10, with Germany in at 3.35. Given Mbappé's return, we predict a high-possession French win.",
        voice: "Kore",
        role: "Analyst",
      },
      {
        speaker: "Expert Charon",
        text: "Remember, predictions are for entertainment only; this is not betting advice. Always play responsibly.",
        voice: "Charon",
        role: "Expert",
      },
    ],
  },
  {
    id: "spon-ad-show",
    title: "Premium Footwear Review",
    matchName: "Sponsored Segment",
    language: "English",
    tone: "Casual",
    durationSeconds: 45,
    showType: "round-up",
    relatedTeamIds: [],
    createdAt: "2026-06-11T12:00:00Z",
    tier: "free",
    isSponsored: true,
    segments: [
      {
        speaker: "Anchor Mike",
        text: "Today's show is brought to you by MaxGear International. Gear up for the World Cup with twenty percent off using promo code RADIO2026 at checkout!",
        voice: "Zephyr",
        role: "Anchor",
      },
    ],
  },
];
